### PR TITLE
Update models.py to be Django 1.9+ compatible

### PR DESCRIPTION
**Pull request by dedayoa**
Django 1.9+ compatible

### CODE REVIEW

**Comment by dedayoa** [comment]
Don't know much about travis, and I'm coding against django 1.9 and Python 3.5. I'm guessing the checks are failing due to this.

**Comment by areski** [comment]
Why do you need to add `MaxValueValidator` in order to make it compatible with Django 1.9 ?

**Comment by dedayoa** [comment]
Hi,

Can't recollect now, but I guess the current implementation (for 
validation) does not work in 1.9.10.

**Comment by areski** [comment]
closing this

**Pull request closed without merging**
